"""Repository protocols — Agent 3 depends on these, not SQLAlchemy."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol, runtime_checkable

from server.models import (
    ActivityEvent,
    Attempt,
    AttemptAnswer,
    Challenge,
    ClassMembership,
    Duel,
    Question,
    QuestionOption,
    SchoolClass,
    StudentStats,
    Subject,
    Topic,
    TopicProgress,
    User,
    XpLedger,
)


@runtime_checkable
class UserRepository(Protocol):
    async def get_by_id(self, user_id: str) -> User | None: ...
    async def get_by_identifier(self, identifier: str) -> User | None: ...
    async def add(self, user: User) -> User: ...
    async def save(self, user: User) -> User: ...


@runtime_checkable
class ClassRepository(Protocol):
    async def get_by_id(self, class_id: str) -> SchoolClass | None: ...
    async def get_by_invite_code(self, invite_code: str) -> SchoolClass | None: ...
    async def add(self, school_class: SchoolClass) -> SchoolClass: ...
    async def list_for_user(self, user_id: str) -> list[SchoolClass]: ...


@runtime_checkable
class MembershipRepository(Protocol):
    async def get(self, class_id: str, user_id: str) -> ClassMembership | None: ...
    async def add(self, membership: ClassMembership) -> ClassMembership: ...
    async def list_by_class(self, class_id: str) -> list[ClassMembership]: ...
    async def is_active_member(self, class_id: str, user_id: str) -> bool: ...


@runtime_checkable
class CurriculumRepository(Protocol):
    async def get_subject(self, subject_id: str) -> Subject | None: ...
    async def list_subjects(self, class_id: str) -> list[Subject]: ...
    async def add_subject(self, subject: Subject) -> Subject: ...
    async def get_topic(self, topic_id: str) -> Topic | None: ...
    async def list_topics(self, subject_id: str) -> list[Topic]: ...
    async def add_topic(self, topic: Topic) -> Topic: ...


@runtime_checkable
class ChallengeRepository(Protocol):
    async def get_by_id(self, challenge_id: str) -> Challenge | None: ...
    async def list_by_topic(self, topic_id: str) -> list[Challenge]: ...
    async def add(self, challenge: Challenge) -> Challenge: ...
    async def get_questions(self, challenge_id: str) -> list[Question]: ...
    async def get_options(self, question_id: str) -> list[QuestionOption]: ...


@runtime_checkable
class AttemptRepository(Protocol):
    async def get_by_id(self, attempt_id: str) -> Attempt | None: ...
    async def add(self, attempt: Attempt) -> Attempt: ...
    async def list_by_user(self, user_id: str, *, limit: int = 50) -> list[Attempt]: ...
    async def get_answer(self, attempt_id: str, question_id: str) -> AttemptAnswer | None: ...
    async def upsert_answer(self, answer: AttemptAnswer) -> AttemptAnswer: ...
    async def list_answers(self, attempt_id: str) -> list[AttemptAnswer]: ...
    async def recent_accuracies_for_topic(
        self, user_id: str, topic_id: str, *, limit: int = 5
    ) -> list[float]: ...


@runtime_checkable
class DuelRepository(Protocol):
    async def get_by_id(self, duel_id: str) -> Duel | None: ...
    async def get_by_share_code(self, share_code: str) -> Duel | None: ...
    async def add(self, duel: Duel) -> Duel: ...
    async def list_for_user(self, user_id: str) -> list[Duel]: ...


@runtime_checkable
class StatsRepository(Protocol):
    async def get_student_stats(self, user_id: str, class_id: str) -> StudentStats | None: ...
    async def ensure_student_stats(self, user_id: str, class_id: str) -> StudentStats: ...
    async def get_topic_progress(self, user_id: str, topic_id: str) -> TopicProgress | None: ...
    async def ensure_topic_progress(self, user_id: str, topic_id: str) -> TopicProgress: ...
    async def list_topic_progress(
        self, user_id: str, *, subject_id: str | None = None
    ) -> list[TopicProgress]: ...
    async def list_class_stats(self, class_id: str) -> list[StudentStats]: ...
    async def add_xp_entry(self, entry: XpLedger) -> XpLedger: ...
    async def xp_entry_exists(self, user_id: str, source_type: str, source_id: str) -> bool: ...
    async def sum_period_xp(self, user_id: str, class_id: str, since: datetime) -> int: ...


@runtime_checkable
class ActivityRepository(Protocol):
    async def add(self, event: ActivityEvent) -> ActivityEvent: ...
    async def list_by_class(
        self, class_id: str, *, limit: int = 50, cursor: datetime | None = None
    ) -> list[ActivityEvent]: ...
